### ISSUE TITLE
One modification on NeurIPS 2020 paper 

### ISSUE THREAD

**Issue by ytaek-oh** [yassouali/awesome-semi-supervised-learning#10]
Hi, I've just checked some of NeurIPS2020 papers are added to this repository.
Additionally, the paper "Unsupervised Data Augmentation for Consistency Training" is accepted on NeurIPS2020, but the information is not modified (the item in year 2019). 

Unsupervised Data Augmentation for Consistency Training.
Qizhe Xie, Zihang Dai, Eduard Hovy, Minh-Thang Luong, Quoc V. Le. NeurIPS 2020

**Comment by yassouali** [comment]
Thank you @ytaek-oh 
Just corrected the yead / conference.
