### ISSUE TITLE
Missing paper information

### ISSUE THREAD

**Issue by ytaek-oh** [yassouali/awesome-semi-supervised-learning#16]
Hi, paper information (authors, conference) is missing for the paper on the list:
Interpolation Consistency Training for Semi-Supervised Learning.

- Interpolation Consistency Training for Semi-Supervised Learning.
  [[pdf]](https://arxiv.org/pdf/1903.03825) 
  [[code]](https://github.com/vikasverma1077/ICT)
  - Vikas Verma, Alex Lamb, Juho Kannala, Yoshua Bengio and David Lopez-Paz. *IJCAI2019*

**Comment by yassouali** [comment]
Thank you, I just fixed it.
