### ISSUE TITLE
would like to contribute papers you likely might have missed

### ISSUE THREAD

**Issue by Shasvat0601** [yassouali/awesome-semi-supervised-learning#2]
Paper 1
Title: `Semi-Supervised Semantic Segmentation with High- and Low-level Consistency`
Conference: `IEEE TPAMI`
Year: `2019`
```
Sudhanshu Mittal, Maxim Tatarchenko, and Thomas
Brox. Semi-supervised semantic segmentation with
high- and low-level consistency. arXiv preprint
arXiv:1908.05724, 2019. 2, 7, 8, 9
```

Paper 2:
Title: `Adversarial learning for semi-supervised semantic segmentation`
Conference: `BMVC`
Year: `2018`

```
Hung, Wei-Chih, et al. "Adversarial learning for semi-supervised semantic segmentation." arXiv preprint arXiv:1802.07934 (2018).
}
```

**Comment by yassouali** [comment]
thank you, I did miss them, I also added two relevent paper I also missed.
