### ISSUE TITLE
A misplaced paper in the Image Classifcation list

### ISSUE THREAD

**Issue by NTU-P04922004** [yassouali/awesome-semi-supervised-learning#32]
Thanks for sharing the paper list of semi-supervised learning (SSL).
This is an awesome resource for studying SSL.

However, I found one paper has been misplaced, and the paper list can be improved.

```
Humble Teachers Teach Better Students for Semi-Supervised Object Detection.
Yihe Tang, Weifeng Chen, Yijun Luo, Yuting Zhang. CVPR 2021
```

I think this paper should be put on the ```Object Detection``` list instead of the ```Image Classifcation``` list.

**Comment by yassouali** [comment]
thank you for the catch, just fixed it
