### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by hasibzunair** [yassouali/awesome-semi-supervised-learning#41]
Hi, 

Requesting to add our paper. 

STAR: Noisy Semi-Supervised Transfer Learning for Visual Classification. [[pdf](https://arxiv.org/abs/2108.08362)]  [[code](https://github.com/Decathlon/decavision)]

Hasib Zunair, Yan Gobeil, Samuel Mercier and A. Ben Hamza. ACM MMSports 2021

**Comment by yassouali** [comment]
done
