### ISSUE TITLE
cvpr 2022 papers

### ISSUE THREAD

**Issue by fawazsammani** [yassouali/awesome-semi-supervised-learning#46]
Hi. Can you please add these CVPR 2022 papers?

SimMatch: Semi-supervised Learning with Similarity Matching
https://arxiv.org/pdf/2203.06915.pdf

Propagation Regularizer for Semi-supervised Learning with Extremely Scarce Labeled Samples
https://openaccess.thecvf.com/content/CVPR2022/papers/Kim_Propagation_Regularizer_for_Semi-Supervised_Learning_With_Extremely_Scarce_Labeled_Samples_CVPR_2022_paper.pdf

DC-SSL: Addressing Mismatched Class Distribution in Semi-supervised Learning
https://openaccess.thecvf.com/content/CVPR2022/papers/Zhao_DC-SSL_Addressing_Mismatched_Class_Distribution_in_Semi-Supervised_Learning_CVPR_2022_paper.pdf

Towards Discovering the Effectiveness of Moderately Confident Samples for Semi-Supervised Learning
https://openaccess.thecvf.com/content/CVPR2022/papers/Tang_Towards_Discovering_the_Effectiveness_of_Moderately_Confident_Samples_for_Semi-Supervised_CVPR_2022_paper.pdf

**Comment by yassouali** [comment]
Sorry for the delayed response @fawazsammani 

Done,
