### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by ChenHsing** [yassouali/awesome-semi-supervised-learning#56]
Hi, I request to add the two papers:

SVFormer: Semi-supervised Video Transformer for Action Recognition , [pdf](https://arxiv.org/abs/2211.13222)
Zhen Xing, Qi Dai, Han Hu, Jingjing Chen, Zuxuan Wu, Yu-Gang Jiang, CVPR 2023

Semi-supervised Single-view 3D Reconstruction via Prototype Shape Priors.  [pdf](https://arxiv.org/abs/2209.15383)
Zhen Xing, Hengduo Li, Zuxuan Wu, Yu-Gang Jiang, ECCV 2022

**Comment by yassouali** [comment]
done, thanks
