### ISSUE TITLE
Suggestion for Paper

### ISSUE THREAD

**Issue by adv010** [yassouali/awesome-semi-supervised-learning#59]
Hi, thanks for maintaining this repo. It is truly awesome ! :)

Request you to add to this list : 
https://openaccess.thecvf.com/content/ICCV2023/papers/Xia_CoIn_Contrastive_Instance_Feature_Mining_for_Outdoor_3D_Object_Detection_ICCV_2023_paper.pdf

3D SSOD paper

**Comment by yassouali** [comment]
Done, thanks
