### ISSUE TITLE
add a new paper

### ISSUE THREAD

**Issue by hasibzunair** [yassouali/awesome-semi-supervised-learning#9]
Hi,

Maybe this can be added.

[Self-training with Noisy Student improves ImageNet classification](https://arxiv.org/abs/1911.04252)
Published in CVPR 2020

**Comment by yassouali** [comment]
Hi, 

Thanks for the suggestion. I think the paper is more of a supervised pretraining approch using a SSL method, a bit different than the ones listes.

**Comment by hasibzunair** [comment]
Alright. Closing this then!

**Comment by yassouali** [comment]
Hi @hasibzunair 

You were right, I've just seen that the method is effective in SSL real-world settings, so the paper is differently relevant to SLL, just added it, sorry for my earlier response,

Thanks.

**Comment by hasibzunair** [comment]
No problem!
